import type { JurisdictionInfo, StateOption } from "./types";

export const US_STATES: StateOption[] = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
  { code: "DC", name: "District of Columbia" },
];

export const US_JURISDICTION: JurisdictionInfo = {
  code: "US",
  name: "United States",
  emoji: "🇺🇸",
  hasStates: true,

  classification: "Property (IRS Notice 2014-21)",
  officialGuidanceUrl: "https://www.irs.gov/businesses/small-businesses-self-employed/virtual-currencies",

  receiptRequirements: {
    mandatoryFields: [
      "date_time",
      "crypto_amount",
      "fiat_amount_usd",
      "description",
      "payer_address",
      "recipient_address",
      "tax_id",
      "transaction_hash",
    ],
    retentionYears: 7,
    notes: "IRS audit period is 3 years normally, 7 years for substantial underreporting",
  },

  transactionTypes: {
    recipient: [
      {
        type: "business_income",
        label: "Business Income",
        description: "Income from business services (freelancing, contracting)",
        taxFormHint: "1099-NEC, Schedule C",
        taxRate: "10-37% federal + state",
        reportingThreshold: 600,
        notes: "Subject to self-employment tax if applicable",
      },
      {
        type: "personal_income",
        label: "Personal Income / Wages",
        description: "Employment wages paid in crypto",
        taxFormHint: "W-2, subject to withholding",
        taxRate: "10-37% federal + state",
      },
      {
        type: "capital_gain",
        label: "Capital Gain",
        description: "Crypto appreciated between acquisition and receipt",
        taxFormHint: "Schedule D, Form 8949",
        taxRate: "0-20% long-term, 10-37% short-term",
      },
      {
        type: "gift_received",
        label: "Gift Received",
        description: "Crypto received as a gift",
        taxFormHint: "Generally not taxable to recipient",
        notes: "Donor may owe gift tax if over annual exclusion ($18,000 in 2024)",
      },
      {
        type: "royalty",
        label: "Royalty / Licensing Income",
        description: "Royalties from intellectual property",
        taxFormHint: "1099-MISC, Schedule E",
        taxRate: "10-37% federal + state",
      },
    ],
    payer: [
      {
        type: "business_expense",
        label: "Business Expense / Purchase",
        description: "Deductible business expense paid with crypto",
        taxFormHint: "Schedule C (Expense Deduction)",
        deductible: true,
        notes: "Must also calculate capital gain/loss on crypto disposal",
      },
      {
        type: "personal_expense",
        label: "Personal Expense",
        description: "Non-deductible personal purchase",
        taxFormHint: "Form 8949 for capital gain/loss only",
        deductible: false,
      },
      {
        type: "capital_loss",
        label: "Capital Loss",
        description: "Crypto depreciated between acquisition and payment",
        taxFormHint: "Schedule D, Form 8949",
        notes: "Can offset capital gains; $3,000 annual limit against ordinary income",
      },
      {
        type: "gift_given",
        label: "Gift Given",
        description: "Crypto given as a gift",
        taxFormHint: "Form 709 if over annual exclusion",
        notes: "No capital gain/loss on gift; basis transfers to recipient",
      },
      {
        type: "charitable_donation",
        label: "Charitable Donation",
        description: "Donation to qualified 501(c)(3) charity",
        taxFormHint: "Schedule A (Itemized Deduction)",
        deductible: true,
        notes: "Deduct FMV if held >1 year; no capital gains tax",
      },
    ],
  },

  costBasisMethods: ["specific_id", "fifo"],
  defaultCostBasisMethod: "fifo",

  holdingPeriodRules: {
    hasDiscount: true,
    longTermThresholdDays: 365,
    longTermRate: "0-20%",
    shortTermRate: "10-37%",
    notes: "Long-term rates: 0% (up to $44,625), 15% ($44,626-$492,300), 20% (over $492,300) for 2024",
  },

  vatGstRules: {
    applicable: false,
    cryptoToFiatExempt: true,
    goodsServicesSubject: false,
    notes: "No federal VAT; state sales tax may apply depending on state",
  },

  specialFeatures: [
    "Form 1099-DA reporting starts 2025 (gross proceeds), 2026 (cost basis)",
    "Specific Identification allows HIFO tax optimization",
    "Backup withholding (24-30%) if no TIN provided",
    "$600 threshold for 1099-NEC reporting",
  ],

  lastUpdated: "2024-10-04",
};
